import QtQuick
import QtMultimedia

// Short, quiet effects generated by tools/gen-sounds.py (original audio).
Item {
  id: bank
  property string baseDir: ""

  readonly property var effects: ({
    pickup: pickup, place: place, valid: valid, invalid: invalid, bingo: bingo, victory: victory
  })

  function play(name) {
    var e = effects[name]
    if (e && e.status === SoundEffect.Ready) e.play()
  }

  function src(name) { return Qt.resolvedUrl("../assets/sounds/" + name + ".wav") }

  SoundEffect { id: pickup; source: bank.src("pickup"); volume: 0.35 }
  SoundEffect { id: place; source: bank.src("place"); volume: 0.45 }
  SoundEffect { id: valid; source: bank.src("valid"); volume: 0.35 }
  SoundEffect { id: invalid; source: bank.src("invalid"); volume: 0.35 }
  SoundEffect { id: bingo; source: bank.src("bingo"); volume: 0.4 }
  SoundEffect { id: victory; source: bank.src("victory"); volume: 0.4 }
}
